# version: "3.9"

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./dishes:/app/dishes:ro
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
    ports:
      - "4173:4173"
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
    depends_on:
      - backend
